# --- !Ups

CREATE TABLE "USER" (
    "EMAIL" VARCHAR(255) PRIMARY KEY CHECK (EMAIL ~* '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'),
    "PASSWORD" VARCHAR(255) NOT NULL CHECK (PASSWORD ~* '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%?&])[A-Za-z\d@$!%?&]{8,}$')
);

INSERT INTO "USER" ("EMAIL","PASSWORD")
VALUES ('admin@gmail.com', 'Admin@123');


INSERT INTO "USER" ("EMAIL","PASSWORD")
VALUES ('abc@gmail.com', 'Srish@14');

INSERT INTO "USER" ("EMAIL","PASSWORD")
VALUES ('xyz@gmail.com', 'Srish&14');

CREATE TABLE CUSTOMER (
    CUSTOMER_ID VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    CONTACT_NO INT,
    ADDRESS VARCHAR(255),
    AGE INT,
    GENDER VARCHAR(1),
    PRIMARY KEY (CUSTOMER_ID),
    FOREIGN KEY (EMAIL) REFERENCES "USER"("EMAIL") ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME,EMAIL,CONTACT_NO,ADDRESS,AGE,GENDER)
VALUES ('c1', 'f1', 'l1', 'abc@gmail.com', '12345', 'Address 1', 18, 'F');

INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME,EMAIL,CONTACT_NO,ADDRESS,AGE,GENDER)
VALUES ('c2', 'f2', 'l2', 'xyz@gmail.com', '12346', 'Address 2', 22, 'M');

CREATE TABLE PRODUCT (
    PRODUCT_ID VARCHAR(255),
    PRODUCT_NAME VARCHAR(255),
    DESCRIPTION TEXT,
    BRAND VARCHAR(100),
    SIZE VARCHAR(50),
    COLOR VARCHAR(50),
    ACTUAL_PRICE DECIMAL(10, 2),
    DISCOUNT DECIMAL(5, 2) CHECK (DISCOUNT >= 1 AND DISCOUNT <= 100),
    RENTAL_PRICE DECIMAL(10, 2),
    SECURITY_CHARGES DECIMAL(10, 2),
    CONVENIENCE_FEE DECIMAL(10,2),
    QUANTITY INT,
    SUSTAINABILITY_RATINGS INT CHECK (SUSTAINABILITY_RATINGS >= 0 AND SUSTAINABILITY_RATINGS <= 5),
    PRIMARY KEY (PRODUCT_ID, SIZE, COLOR)
);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, DESCRIPTION, BRAND, SIZE, COLOR, ACTUAL_PRICE, DISCOUNT, RENTAL_PRICE, SECURITY_CHARGES, CONVENIENCE_FEE, QUANTITY, SUSTAINABILITY_RATINGS)
VALUES ('p1', 'Product 1', 'Description of Product 1', 'Brand 1', 'S', 'Red', 1000, 10, 50, 0, 0, 5, 4);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, DESCRIPTION, BRAND, SIZE, COLOR, ACTUAL_PRICE, DISCOUNT, RENTAL_PRICE, SECURITY_CHARGES, CONVENIENCE_FEE, QUANTITY, SUSTAINABILITY_RATINGS)
VALUES ('p1', 'Product 1', 'Description of Product 1', 'Brand 1', 'M', 'Red', 1000, 10, 50, 0, 0, 5, 4);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, DESCRIPTION, BRAND, SIZE, COLOR, ACTUAL_PRICE, DISCOUNT, RENTAL_PRICE, SECURITY_CHARGES, CONVENIENCE_FEE, QUANTITY, SUSTAINABILITY_RATINGS)
VALUES ('p2', 'Product 2', 'Description of Product 2', 'Brand 2', 'M', 'Blue', 1200, 10, 60, 0, 0, 6, 5);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, DESCRIPTION, BRAND, SIZE, COLOR, ACTUAL_PRICE, DISCOUNT, RENTAL_PRICE, SECURITY_CHARGES, CONVENIENCE_FEE, QUANTITY, SUSTAINABILITY_RATINGS)
VALUES ('p3', 'Product 3', 'Description of Product 3', 'Brand 3', 'M', 'Pink', 1500, 10, 40, 0, 0, 7, 5);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, DESCRIPTION, BRAND, SIZE, COLOR, ACTUAL_PRICE, DISCOUNT, RENTAL_PRICE, SECURITY_CHARGES, CONVENIENCE_FEE, QUANTITY, SUSTAINABILITY_RATINGS)
VALUES ('p4', 'Product 4', 'Description of Product 4', 'Brand 4', 'S', 'Baby Pink', 1100, 10, 30, 0, 0, 3, 4);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, DESCRIPTION, BRAND, SIZE, COLOR, ACTUAL_PRICE, DISCOUNT, RENTAL_PRICE, SECURITY_CHARGES, CONVENIENCE_FEE, QUANTITY, SUSTAINABILITY_RATINGS)
VALUES ('p4', 'Product 4', 'Description of Product 4', 'Brand 4', 'M', 'Baby Pink', 1100, 10, 30, 0, 0, 3, 4);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, DESCRIPTION, BRAND, SIZE, COLOR, ACTUAL_PRICE, DISCOUNT, RENTAL_PRICE, SECURITY_CHARGES, CONVENIENCE_FEE, QUANTITY, SUSTAINABILITY_RATINGS)
VALUES ('p4', 'Product 4', 'Description of Product 4', 'Brand 4', 'S', 'Pink', 1100, 10, 30, 0, 0, 3, 4);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, DESCRIPTION, BRAND, SIZE, COLOR, ACTUAL_PRICE, DISCOUNT, RENTAL_PRICE, SECURITY_CHARGES, CONVENIENCE_FEE, QUANTITY, SUSTAINABILITY_RATINGS)
VALUES ('p4', 'Product 4', 'Description of Product 4', 'Brand 4', 'M', 'Pink', 1100, 10, 30, 0, 0, 3, 4);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, DESCRIPTION, BRAND, SIZE, COLOR, ACTUAL_PRICE, DISCOUNT, RENTAL_PRICE, SECURITY_CHARGES, CONVENIENCE_FEE, QUANTITY, SUSTAINABILITY_RATINGS)
VALUES ('p4', 'Product 4', 'Description of Product 4', 'Brand 4', 'S', 'Purple', 1100, 10, 30, 0, 0, 3, 4);

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, DESCRIPTION, BRAND, SIZE, COLOR, ACTUAL_PRICE, DISCOUNT, RENTAL_PRICE, SECURITY_CHARGES, CONVENIENCE_FEE, QUANTITY, SUSTAINABILITY_RATINGS)
VALUES ('p4', 'Product 4', 'Description of Product 4', 'Brand 4', 'M', 'Purple', 1100, 10, 30, 0, 0, 3, 4);



CREATE TABLE PRODUCT_CATEGORY (
    PRODUCT_ID VARCHAR(255),
    SIZE VARCHAR(50),
    COLOR VARCHAR(50),
    CATEGORY_NAME VARCHAR(255),
    PRIMARY KEY (PRODUCT_ID, SIZE, COLOR, CATEGORY_NAME),
    FOREIGN KEY (PRODUCT_ID, SIZE, COLOR) REFERENCES PRODUCT(PRODUCT_ID, SIZE, COLOR) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO PRODUCT_CATEGORY (PRODUCT_ID, SIZE, COLOR, CATEGORY_NAME)
VALUES
    ('p1', 'S', 'Red', 'p1c1'),
    ('p1', 'S', 'Red', 'p1c2'),
    ('p1', 'M', 'Red', 'p1c1'),
    ('p1', 'M', 'Red', 'p1c2'),
    ('p2', 'M', 'Blue', 'p2c1'),
    ('p3', 'M', 'Pink', 'p3c1'),
    ('p4', 'S', 'Baby Pink', 'p4c1'),
    ('p4', 'S', 'Baby Pink', 'p4c2'),
    ('p4', 'M', 'Baby Pink', 'p4c1'),
    ('p4', 'M', 'Baby Pink', 'p4c2'),
    ('p4', 'S', 'Pink', 'p4c1'),
    ('p4', 'S', 'Pink', 'p4c2'),
    ('p4', 'M', 'Pink', 'p4c1'),
    ('p4', 'M', 'Pink', 'p4c2'),
    ('p4', 'S', 'Purple', 'p4c1'),
    ('p4', 'S', 'Purple', 'p4c2'),
    ('p4', 'M', 'Purple', 'p4c1'),
    ('p4', 'M', 'Purple', 'p4c2');

CREATE TABLE PRODUCT_MATERIAL (
    PRODUCT_ID VARCHAR(255),
    SIZE VARCHAR(50),
    COLOR VARCHAR(50),
    MATERIAL_NAME VARCHAR(255),
    PRIMARY KEY (PRODUCT_ID, SIZE, COLOR, MATERIAL_NAME),
    FOREIGN KEY (PRODUCT_ID, SIZE, COLOR) REFERENCES PRODUCT(PRODUCT_ID, SIZE, COLOR) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO PRODUCT_MATERIAL (PRODUCT_ID, SIZE, COLOR, MATERIAL_NAME)
VALUES
    ('p1', 'S', 'Red', 'p1m1'),
    ('p1', 'M', 'Red', 'p1m1'),
    ('p2', 'M', 'Blue', 'p2m1'),
    ('p3', 'M', 'Pink', 'p3m1'),
    ('p4', 'S', 'Baby Pink', 'p4m1'),
    ('p4', 'M', 'Baby Pink', 'p4m1'),
    ('p4', 'S', 'Pink', 'p4m1'),
    ('p4', 'M', 'Pink', 'p4m2'),
    ('p4', 'S', 'Purple', 'p4m1'),
    ('p4', 'M', 'Purple', 'p4m2');

CREATE TABLE ORDER_DETAILS (
    ORDER_ID VARCHAR(255),
    CUSTOMER_ID VARCHAR(255),
    ORDER_ADDRESS VARCHAR(255),
    TOTAL DECIMAL(10, 2),
    PAYMENT_ID VARCHAR(255),
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO ORDER_DETAILS (ORDER_ID, CUSTOMER_ID, ORDER_ADDRESS, TOTAL, PAYMENT_ID)
VALUES ('1', 'c1', 'Address 1', 200, 'payment1');

INSERT INTO ORDER_DETAILS (ORDER_ID, CUSTOMER_ID, ORDER_ADDRESS, TOTAL, PAYMENT_ID)
VALUES ('2', 'c2', 'Address 2', 50, 'payment2');

CREATE TABLE ORDER_ITEMS (
    ORDER_ID VARCHAR(255),
    PRODUCT_ID VARCHAR(255),
    SIZE VARCHAR(255),
    COLOR VARCHAR(255),
    QUANTITY DECIMAL(10, 2),
    ORDER_STATUS VARCHAR(255),
    PRIMARY KEY (ORDER_ID,PRODUCT_ID,SIZE,COLOR),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDER_DETAILS(ORDER_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID,SIZE,COLOR) REFERENCES PRODUCT(PRODUCT_ID,SIZE,COLOR) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, SIZE, COLOR, QUANTITY, ORDER_STATUS)
VALUES ('1', 'p1', 'S', 'Red', 2, 'Confirmed');

INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, SIZE, COLOR, QUANTITY, ORDER_STATUS)
VALUES ('1', 'p2', 'M', 'Blue', 1, 'Shipped');

INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, SIZE, COLOR, QUANTITY, ORDER_STATUS)
VALUES ('1', 'p3', 'M', 'Pink', 1, 'Shipped');

INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, SIZE, COLOR, QUANTITY, ORDER_STATUS)
VALUES ('2', 'p1', 'M', 'Red', 1, 'Shipped');

CREATE TABLE CART (
    EMAIL VARCHAR(255),
    PRODUCT_ID VARCHAR(255),
    SIZE VARCHAR(255),
    COLOR VARCHAR(255),
    QUANTITY INT,
    PRIMARY KEY (EMAIL,PRODUCT_ID,SIZE,COLOR),
    FOREIGN KEY (EMAIL) REFERENCES "USER"("EMAIL") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID,SIZE,COLOR) REFERENCES PRODUCT(PRODUCT_ID,SIZE,COLOR) ON UPDATE CASCADE ON DELETE CASCADE
);

# --- !Downs

DROP TABLE ORDER_ITEMS IF EXISTS;

DROP TABLE ORDER_DETAILS IF EXISTS;

DROP TABLE CART IF EXISTS;

DROP TABLE PRODUCT_CATEGORY IF EXISTS;

DROP TABLE PRODUCT_MATERIAL IF EXISTS;

DROP TABLE PRODUCT IF EXISTS;

DROP TABLE CUSTOMER IF EXISTS;

DROP TABLE "USER" IF EXISTS;

